// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0290:Usar constructor principal", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.UnitTests.Infrastructure.Repositories.VehicleRepositoryForTest.#ctor(MongoDB.Driver.IMongoCollection{GtMotive.Estimate.Microservice.Domain.Entities.Vehicle})")]
[assembly: SuppressMessage("Maintainability", "CA1515:Considere la posibilidad de hacer que los tipos públicos sean internos", Justification = "<pendiente>", Scope = "type", Target = "~T:GtMotive.Estimate.Microservice.UnitTests.Infrastructure.Repositories.VehicleRepositoryForTest")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "No se requiere documentación XML en tests unitarios.")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1601:Partial elements should be documented", Justification = "No se requiere documentación XML en tests unitarios.")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:Enumeration items should be documented", Justification = "No se requiere documentación XML en tests unitarios.")]
[assembly: SuppressMessage("Style", "IDE0049:Simplify Names", Justification = "No se requiere para tests.")]
[assembly: SuppressMessage("Style", "CS1591", Justification = "No se requiere documentación XML en tests unitarios.")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1606:Element documentation should have summary text", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.UnitTests.Api.VehiclesControllerTests.GetVehicleReturnsOkWhenVehicleExists~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1606:Element documentation should have summary text", Justification = "<pendiente>", Scope = "type", Target = "~T:GtMotive.Estimate.Microservice.UnitTests.Api.VehiclesControllerTests")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1606:Element documentation should have summary text", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.UnitTests.Infrastructure.Repositories.VehicleRepositoryForTest.#ctor(MongoDB.Driver.IMongoCollection{GtMotive.Estimate.Microservice.Domain.Entities.Vehicle})")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1606:Element documentation should have summary text", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.UnitTests.Infrastructure.Repositories.VehicleRepositoryForTest.GetByIdAsync(System.Guid)~System.Threading.Tasks.Task{GtMotive.Estimate.Microservice.Domain.Entities.Vehicle}")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1611:Element parameters should be documented", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.UnitTests.Infrastructure.Repositories.VehicleRepositoryForTest.GetByIdAsync(System.Guid)~System.Threading.Tasks.Task{GtMotive.Estimate.Microservice.Domain.Entities.Vehicle}")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1611:Element parameters should be documented", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.UnitTests.Infrastructure.Repositories.VehicleRepositoryForTest.#ctor(MongoDB.Driver.IMongoCollection{GtMotive.Estimate.Microservice.Domain.Entities.Vehicle})")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1606:Element documentation should have summary text", Justification = "<pendiente>", Scope = "type", Target = "~T:GtMotive.Estimate.Microservice.UnitTests.Infrastructure.Repositories.VehicleRepositoryForTest")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1606:Element documentation should have summary text", Justification = "<pendiente>", Scope = "type", Target = "~T:GtMotive.Estimate.Microservice.UnitTests.Infrastructure.VehicleRepositoryTests")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.UnitTests.Infrastructure.Repositories.VehicleRepositoryForTest.GetByIdAsync(System.Guid)~System.Threading.Tasks.Task{GtMotive.Estimate.Microservice.Domain.Entities.Vehicle}")]
[assembly: SuppressMessage("Style", "IDE0028:Simplificar la inicialización de la recopilación", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.UnitTests.Infrastructure.VehicleRepositoryTests.GetByIdAsyncReturnsVehicleWhenExists~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Major Bug", "S1751:Loops with at most one iteration should be refactored", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.UnitTests.Infrastructure.Repositories.VehicleRepositoryForTest.GetByIdAsync(System.Guid)~System.Threading.Tasks.Task{GtMotive.Estimate.Microservice.Domain.Entities.Vehicle}")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1606:Element documentation should have summary text", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.UnitTests.ApplicationCore.Vehicles.GetVehicleUseCaseTests.ExecuteCallsStandardHandleWhenVehicleExists~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1606:Element documentation should have summary text", Justification = "<pendiente>", Scope = "type", Target = "~T:GtMotive.Estimate.Microservice.UnitTests.ApplicationCore.Vehicles.GetVehicleUseCaseTests")]
