// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
// Review

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Major Code Smell", "S6960:Controllers should not have mixed responsibilities", Justification = "<pendiente>", Scope = "type", Target = "~T:GtMotive.Estimate.Microservice.Api.Controllers.FleetController")]
[assembly: SuppressMessage("Major Code Smell", "S6960:Controllers should not have mixed responsibilities", Justification = "<pendiente>", Scope = "type", Target = "~T:GtMotive.Estimate.Microservice.Api.Controllers.RentController")]
[assembly: SuppressMessage("Major Code Smell", "S6960:Controllers should not have mixed responsibilities", Justification = "<pendiente>", Scope = "type", Target = "~T:GtMotive.Estimate.Microservice.Api.Controllers.VehicleController")]
[assembly: SuppressMessage("Major Code Smell", "S107:Methods should not have too many parameters", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.Api.Controllers.FleetController.#ctor(GtMotive.Estimate.Microservice.ApplicationCore.UseCases.IUseCaseWithPresenter{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.GetFleetUseCaseInput,GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.GetFleetUseCaseOutput},GtMotive.Estimate.Microservice.ApplicationCore.UseCases.IUseCaseWithPresenter{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.GetFleetsUseCaseInput,GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.GetFleetsUseCaseOutput},GtMotive.Estimate.Microservice.ApplicationCore.UseCases.IUseCaseWithPresenter{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.GetVehiclesByFleetUseCaseInput,GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.GetVehiclesByFleetUseCaseOutput},GtMotive.Estimate.Microservice.ApplicationCore.UseCases.IUseCaseWithPresenter{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.AddVehicleToFleetUseCaseInput,GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.AddVehicleToFleetUseCaseOutput},GtMotive.Estimate.Microservice.Api.UseCases.FleetPresenter{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.GetFleetUseCaseOutput},GtMotive.Estimate.Microservice.Api.UseCases.FleetPresenter{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.GetFleetsUseCaseOutput},GtMotive.Estimate.Microservice.Api.UseCases.FleetPresenter{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.GetVehiclesByFleetUseCaseOutput},GtMotive.Estimate.Microservice.Api.UseCases.FleetPresenter{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.AddVehicleToFleetUseCaseOutput})")]

[assembly: SuppressMessage("Style", "IDE0290:Usar constructor principal", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.Api.Controllers.FleetController.#ctor(GtMotive.Estimate.Microservice.ApplicationCore.UseCases.IUseCaseWithPresenter{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.GetFleetUseCaseInput,GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.GetFleetUseCaseOutput},GtMotive.Estimate.Microservice.ApplicationCore.UseCases.IUseCaseWithPresenter{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.GetFleetsUseCaseInput,GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.GetFleetsUseCaseOutput},GtMotive.Estimate.Microservice.ApplicationCore.UseCases.IUseCaseWithPresenter{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.GetVehiclesByFleetUseCaseInput,GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.GetVehiclesByFleetUseCaseOutput},GtMotive.Estimate.Microservice.ApplicationCore.UseCases.IUseCaseWithPresenter{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.AddVehicleToFleetUseCaseInput,GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.AddVehicleToFleetUseCaseOutput},GtMotive.Estimate.Microservice.Api.UseCases.FleetPresenter{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.GetFleetUseCaseOutput},GtMotive.Estimate.Microservice.Api.UseCases.FleetPresenter{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.GetFleetsUseCaseOutput},GtMotive.Estimate.Microservice.Api.UseCases.FleetPresenter{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.GetVehiclesByFleetUseCaseOutput},GtMotive.Estimate.Microservice.Api.UseCases.FleetPresenter{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.AddVehicleToFleetUseCaseOutput})")]
[assembly: SuppressMessage("Style", "IDE0290:Usar constructor principal", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.Api.Controllers.RentController.#ctor(GtMotive.Estimate.Microservice.ApplicationCore.UseCases.IUseCaseWithPresenter{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Rent.GetRentsUseCaseInput,GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Rent.GetRentsUseCaseOutput},GtMotive.Estimate.Microservice.ApplicationCore.UseCases.IUseCaseWithPresenter{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Rent.RentVehicleUseCaseInput,GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Rent.RentVehicleUseCaseOutput},GtMotive.Estimate.Microservice.ApplicationCore.UseCases.IUseCaseWithPresenter{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Rent.ReturnVehicleUseCaseInput,GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Rent.ReturnVehicleUseCaseOutput},GtMotive.Estimate.Microservice.Api.UseCases.RentPresenter{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Rent.GetRentsUseCaseOutput},GtMotive.Estimate.Microservice.Api.UseCases.RentPresenter{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Rent.RentVehicleUseCaseOutput},GtMotive.Estimate.Microservice.Api.UseCases.RentPresenter{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Rent.ReturnVehicleUseCaseOutput})")]
[assembly: SuppressMessage("Style", "IDE0290:Usar constructor principal", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.Api.Controllers.VehicleController.#ctor(GtMotive.Estimate.Microservice.ApplicationCore.UseCases.IUseCaseWithPresenter{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Vehicle.GetVehiclesUseCaseInput,GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Vehicle.GetVehiclesUseCaseOutput},GtMotive.Estimate.Microservice.ApplicationCore.UseCases.IUseCaseWithPresenter{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Vehicle.GetVehicleUseCaseInput,GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Vehicle.GetVehicleUseCaseOutput},GtMotive.Estimate.Microservice.ApplicationCore.UseCases.IUseCaseWithPresenter{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Vehicle.CreateVehicleUseCaseInput,GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Vehicle.CreateVehicleUseCaseOutput},GtMotive.Estimate.Microservice.Api.UseCases.VehiclePresenter{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Vehicle.GetVehiclesUseCaseOutput},GtMotive.Estimate.Microservice.Api.UseCases.VehiclePresenter{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Vehicle.GetVehicleUseCaseOutput},GtMotive.Estimate.Microservice.Api.UseCases.VehiclePresenter{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Vehicle.CreateVehicleUseCaseOutput})")]
