// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0290:Usar constructor principal", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.AddVehicleToFleetUseCase.#ctor(GtMotive.Estimate.Microservice.ApplicationCore.Interfaces.IFleetRepository,GtMotive.Estimate.Microservice.ApplicationCore.Interfaces.IVehicleRepository,GtMotive.Estimate.Microservice.Domain.Interfaces.IAppLogger{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.AddVehicleToFleetUseCase})")]
[assembly: SuppressMessage("Style", "IDE0290:Usar constructor principal", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Rent.ReturnVehicleUseCase.#ctor(GtMotive.Estimate.Microservice.ApplicationCore.Interfaces.IRentRepository,GtMotive.Estimate.Microservice.ApplicationCore.Interfaces.IVehicleRepository,GtMotive.Estimate.Microservice.Domain.Interfaces.IAppLogger{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Rent.ReturnVehicleUseCase})")]
[assembly: SuppressMessage("Style", "IDE0290:Usar constructor principal", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.GetFleetsUseCase.#ctor(GtMotive.Estimate.Microservice.ApplicationCore.Interfaces.IFleetRepository,GtMotive.Estimate.Microservice.Domain.Interfaces.IAppLogger{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.GetFleetsUseCase},AutoMapper.IMapper)")]
[assembly: SuppressMessage("Style", "IDE0290:Usar constructor principal", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.GetFleetUseCase.#ctor(GtMotive.Estimate.Microservice.ApplicationCore.Interfaces.IFleetRepository,GtMotive.Estimate.Microservice.Domain.Interfaces.IAppLogger{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.GetFleetUseCase},AutoMapper.IMapper)")]
[assembly: SuppressMessage("Style", "IDE0290:Usar constructor principal", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.GetVehiclesByFleetUseCase.#ctor(GtMotive.Estimate.Microservice.ApplicationCore.Interfaces.IVehicleRepository,GtMotive.Estimate.Microservice.Domain.Interfaces.IAppLogger{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.GetVehiclesByFleetUseCase},AutoMapper.IMapper)")]
[assembly: SuppressMessage("Style", "IDE0290:Usar constructor principal", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Rent.GetRentsUseCase.#ctor(GtMotive.Estimate.Microservice.ApplicationCore.Interfaces.IRentRepository,GtMotive.Estimate.Microservice.Domain.Interfaces.IAppLogger{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Rent.RentVehicleUseCase},AutoMapper.IMapper)")]
[assembly: SuppressMessage("Style", "IDE0290:Usar constructor principal", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Rent.RentVehicleUseCase.#ctor(GtMotive.Estimate.Microservice.ApplicationCore.Interfaces.IRentRepository,GtMotive.Estimate.Microservice.ApplicationCore.Interfaces.IVehicleRepository,GtMotive.Estimate.Microservice.ApplicationCore.Interfaces.IClientRepository,GtMotive.Estimate.Microservice.Domain.Interfaces.IAppLogger{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Rent.RentVehicleUseCase},AutoMapper.IMapper)")]
[assembly: SuppressMessage("Style", "IDE0290:Usar constructor principal", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Vehicle.CreateVehicleUseCase.#ctor(GtMotive.Estimate.Microservice.ApplicationCore.Interfaces.IVehicleRepository,GtMotive.Estimate.Microservice.ApplicationCore.Interfaces.IFleetRepository,GtMotive.Estimate.Microservice.Domain.Interfaces.IAppLogger{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Vehicle.CreateVehicleUseCase},AutoMapper.IMapper)")]
[assembly: SuppressMessage("Style", "IDE0290:Usar constructor principal", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Vehicle.GetVehiclesUseCase.#ctor(GtMotive.Estimate.Microservice.ApplicationCore.Interfaces.IVehicleRepository,GtMotive.Estimate.Microservice.Domain.Interfaces.IAppLogger{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Vehicle.GetVehicleUseCase},AutoMapper.IMapper)")]
[assembly: SuppressMessage("Style", "IDE0290:Usar constructor principal", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Vehicle.GetVehicleUseCase.#ctor(GtMotive.Estimate.Microservice.ApplicationCore.Interfaces.IVehicleRepository,GtMotive.Estimate.Microservice.Domain.Interfaces.IAppLogger{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Vehicle.GetVehicleUseCase},AutoMapper.IMapper)")]

[assembly: SuppressMessage("Style", "IDE0305:Simplificar la inicialización de la recopilación", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Rent.GetRentsUseCase.Execute(GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Rent.GetRentsUseCaseInput,GtMotive.Estimate.Microservice.ApplicationCore.UseCases.IOutputPortStandard{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Rent.GetRentsUseCaseOutput},GtMotive.Estimate.Microservice.ApplicationCore.UseCases.IOutputPortNotFound,GtMotive.Estimate.Microservice.ApplicationCore.UseCases.IOutputPortValidation)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0305:Simplificar la inicialización de la recopilación", Justification = "<pendiente>", Scope = "member", Target = "~M:GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Vehicle.GetVehiclesUseCase.Execute(GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Vehicle.GetVehiclesUseCaseInput,GtMotive.Estimate.Microservice.ApplicationCore.UseCases.IOutputPortStandard{GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Vehicle.GetVehiclesUseCaseOutput},GtMotive.Estimate.Microservice.ApplicationCore.UseCases.IOutputPortNotFound,GtMotive.Estimate.Microservice.ApplicationCore.UseCases.IOutputPortValidation)~System.Threading.Tasks.Task")]

[assembly: SuppressMessage("Design", "CA1002:No exponer listas genéricas", Justification = "<pendiente>", Scope = "member", Target = "~P:GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.GetVehiclesByFleetUseCaseOutput.Vehicles")]
[assembly: SuppressMessage("Design", "CA1002:No exponer listas genéricas", Justification = "<pendiente>", Scope = "member", Target = "~P:GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.GetFleetsUseCaseOutput.Fleets")]
[assembly: SuppressMessage("Design", "CA1002:No exponer listas genéricas", Justification = "<pendiente>", Scope = "member", Target = "~P:GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Rent.GetRentsUseCaseOutput.Rents")]
[assembly: SuppressMessage("Design", "CA1002:No exponer listas genéricas", Justification = "<pendiente>", Scope = "member", Target = "~P:GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Vehicle.GetVehiclesUseCaseOutput.Vehicles")]

[assembly: SuppressMessage("Usage", "CA2227:Las propiedades de colección deben ser de solo lectura", Justification = "<pendiente>", Scope = "member", Target = "~P:GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.GetVehiclesByFleetUseCaseOutput.Vehicles")]
[assembly: SuppressMessage("Usage", "CA2227:Las propiedades de colección deben ser de solo lectura", Justification = "<pendiente>", Scope = "member", Target = "~P:GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Fleet.GetFleetsUseCaseOutput.Fleets")]
[assembly: SuppressMessage("Usage", "CA2227:Las propiedades de colección deben ser de solo lectura", Justification = "<pendiente>", Scope = "member", Target = "~P:GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Rent.GetRentsUseCaseOutput.Rents")]
[assembly: SuppressMessage("Usage", "CA2227:Las propiedades de colección deben ser de solo lectura", Justification = "<pendiente>", Scope = "member", Target = "~P:GtMotive.Estimate.Microservice.ApplicationCore.UseCases.Vehicle.GetVehiclesUseCaseOutput.Vehicles")]
